### ISSUE TITLE
default value for matchable inputs not found

### ISSUE THREAD

**Issue by daroczig** [Rapporter/rapport#81]
Run the below template that should work out-of-the-box without specifying `v` if I am right:

```
<!--head
meta:
  title: Minimal example for default value bug with matchable inputs
  description: Minimal example for default value bug with matchable inputs
  author: daroczig
inputs:
- required: yes
  class: character
  name: v
  label: v
  standalone: yes
  value: Tom
  description: v
  matchable: yes
  options:
  - Tom
  - Jerry
head-->

<%= v %>
```
